version: '3.1'

services:
  robust-nodejs-backend:
    container_name: robust-nodejs-backend-local
    ports:
      - 8080:3000
  
  robust-nodejs-db:
    container_name: robust-nodejs-db-local
    image: "postgres:13"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  robust-nodejs-elasticsearch:
    container_name: robust-nodejs-elasticsearch-local

  robust-nodejs-logstash:
    container_name: robust-nodejs-logstash-local

  robust-nodejs-kibana:
    container_name: robust-nodejs-kibana-local


# networks:
#   myapp_network:
#     name: myapp_network