---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: nodejs-robus-kibana-docker
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://robust-nodejs-elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: elastic
elasticsearch.password: mcdonalds4ever
